# : Manager [[[

[mgr]
cwd = { fg = "#e5e2e0" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#c1a3b8", bg = "#c1a3b8" }
marker_cut      = { fg = "#eae0e7", bg = "#eae0e7" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#cdc4cb", bg = "#cdc4cb" }

# Count
count_copied   = { fg = "#1f1a1f", bg = "#eae0e7" }
count_cut      = { fg = "#1f1a1f", bg = "#eae0e7" }
count_selected = { fg = "#313128", bg = "#cdc4cb" }

# Border
border_symbol = "│"
border_style  = { fg = "#c9c7ba" }

# : ]]]


# : Tabs (New Section) [[[

[tabs]
active    = { fg = "#313128", bg = "#c9c7ba", bold = true }
inactive  = { fg = "#e6e3d6", bg = "#1c1c14" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c9c7ba", fg = "#313128", bold = true }
normal_alt  = { bg = "#48473f", fg = "#c9c6bd" }

# Select mode
select_main = { bg = "#c9c6c0", fg = "#31302c", bold = true }
select_alt  = { bg = "#48473f", fg = "#c9c6bd" }

# Unset mode
unset_main = { bg = "#cdc4cb", fg = "#342f34", bold = true }
unset_alt  = { bg = "#48473f", fg = "#c9c6bd" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c9c7ba", bg = "#3a3938" }
progress_error  = { fg = "#ffb4ab", bg = "#3a3938" }

# Permissions
perm_type  = { fg = "#817b6f" }
perm_write = { fg = "#867282" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ac85a0" }
perm_sep   = { fg = "#aca277" }

# : ]]]


# : Picker (Renamed from Select) [[[

[pick]
border   = { fg = "#c9c7ba" }
active   = { fg = "#cdc4cb", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c9c7ba" }
value  = { fg = "#e5e2e0" }

# : ]]]


# : Completion (Renamed from Completion) [[[

[cmp]
border = { fg = "#c9c7ba", bg = "#313128" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#c9c7ba" }
title   = {}
hovered = { fg = "#eae0e7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a3938" }
cand = { fg = "#c9c7ba" }
rest = { fg = "#313128" }
desc = { fg = "#e5e2e0" }
separator = " ▶ "
separator_style = { fg = "#e5e2e0" }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e5e2e0" }
run    = { fg = "#e5e2e0" }
footer = { fg = "#31302c", bg = "#c9c6c0" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#cdc4cb" }
title_warn  = { fg = "#c9c7ba" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e5e2e0" },
    { url = "*/", fg = "#c9c7ba" },
]

# : ]]]

