# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: deepseek:deepseek-chat
clients:
  - type: openai-compatible
    name: deepseek
    api_base: https://api.deepseek.com
    # api_key 在 secrets.fish 中通过 DEEPSEEK_API_KEY 环境变量提供
